# Additional Resources {#additional-resources}

## PsyTeachR Resources 

If you would like additional practice, you can check out the other University of Glasgow PsyTeachR course books: 

* [Level 1](https://psyteachr.github.io/data-skills-v3/): Our first-year introduction to R focusing on data wrangling, data visualisation, and descriptive statistics.

* [Level 2](https://psyteachr.github.io/analysis-v4/): Our second-year undergraduate course introduces statistical concepts such as t-tests, NHST, alpha, power, effect size, and sample size. Semester 2 focuses on correlations and the general linear model. 

* [Level 3](https://psyteachr.github.io/stat-models-v1/): This third-year undergraduate course teaches students how to specify, estimate, and interpret statistical models corresponding to various study designs, using a General Linear Models approach.

* [Data Skills for Reproducible Research](https://psyteachr.github.io/reprores-v5/): This course covers our MSc suite of degrees and provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, and reproducible workflows.

* [Statistics and Research Design](https://psyteachr.github.io/statsres-v2/): This course builds on *Data Skills for Reproducible Research* for our MSc suite of degrees. Students take their reproducible data skills and learn advanced modelling techniques from the general linear model, robust statistics, and Bayesian statistics. 

* [Data Analysis Journeys](https://psyteachr.github.io/analysis_journeys/): We link to this book several times in this book. We provide different data sets and activities for you to test your skills on. They are less structured than the book and represent the next step in your learning journey in being able to identify the code you need, but still being able to compare your answer to a solution. 

## Other Resources

We also highly recommend the following, they will help practice your data wrangling skills but also they're great options if you're enjoying R and want to stretch yourself:

* [Open Stats Lab](https://sites.trinity.edu/osl) - this wonderful resource gives you practice at running statistical tests by providing you with datasets from published papers.

* [R for Data Science](https://r4ds.hadley.nz/) - written by the authors of the tidyverse, this is a great resource for additional data wrangling practice and more depth on many of the tidyverse functions.

* [Text Mining with R](https://www.tidytextmining.com/) - Shows you how to use R to work with text. This isn't something we cover in this course, but it uses the same data wrangling skills and be a very useful additional skill to have.

* [How to make BBC style graphics](https://bbc.github.io/rcookbook/#how_to_create_bbc_style_graphics) - Ever wondered how the BBC News makes their data visualisation? Well, now you can make your own!

* [Data Vizualisation](https://socviz.co/) - this is an entire book on data visualisation and goes into detail on how to take `ggplot` to its limits. 
