# Overview {.unnumbered}

**Book Name:** Fundamentals of Quantitative Analysis.

**Summary:** Materials for the MSc Conversion Research Methods 1 and 2 courses at the University of Glasgow School of Psychology & Neuroscience. 

**Authors:** James Bartlett and Wil Toivo. This version of the book was adapted from a previous version written by Emily Nordmann and Phil McAleer. 

**Aim:** This course covers data skills such as creating reproducible documents with R Markdown, data wrangling, and data visualisation with the tidyverse family of packages. It also introduces statistical concepts such as Null Hypothesis Significance Testing (NHST), as well as demonstrating how to perform numerous analyses based around the general linear model including regression and ANOVA.

**Contact:** This book is a living document and will be regularly checked and updated for improvements. Should you have any issues using the book or have any queries, please contact [James Bartlett](mailto:james.bartlett@glasgow.ac.uk) and [Wil Toivo](mailto:wilhelmiina.toivo@glasgow.ac.uk).

```{r, echo=FALSE}
version <- R.version.string

last_updated <- Sys.Date()
```

The online version of the book will always be the most up-to-date version with interactive exercises. Periodically, we create a PDF version of the book if that helps you work offline. We last knitted the book on `r last_updated`. 

**R Version:** We wrote this book using `r version`.


