{
  "hash": "9dc93f87e6b054ea2ea18803991779ef",
  "result": {
    "engine": "knitr",
    "markdown": "# Equivalence Testing {#equivalence}\n\n\n\n\n\n\n\n\n\n\n\n\n\nIn this bonus chapter, you will learn how to apply equivalence testing. In Chapters 8 and 9, you learnt about different inferential statistics but they all rely on the traditional null hypothesis significance testing framework of rejecting a null value of zero. The limitations of this approach is that you can only ever test to reject the null, not test *for* the null, or more precisely for effect sizes within a set of boundaries. In this chapter, you will learn how to use the <pkg>TOSTER</pkg> package to apply equivalence testing to t-tests and correlations. \n\n**Chapter Intended Learning Outcomes (ILOs)**\n\nBy the end of this chapter, you will be able to: \n\n- Justify your equivalence boundaries for your smallest effect size of interest.   \n\n- Apply equivalence testing to designs requiring a correlation. \n\n- Apply equivalence testing to designs requiring a t-test. \n\n## Chapter preparation\n\n### Organising your files and project for the chapter\n\nFor this chapter, we are going to revisit the data sets you worked with in Chapters 8 [@dawtry_why_2015] and 9 [@lopez_visual_2023]. Before we can get started, you need to organise your files and project for the chapter, so your working directory is in order.\n\n1. In your folder for research methods and the book `ResearchMethods1_2/Quant_Fundamentals`, create a new folder called `Equivalence_testing`. Within `Equivalence_testing`, create two new folders called `data` and `figures`.\n\n2. Create an R Project for `Equivalence_testing` as an existing directory for your chapter folder. This should now be your working directory.\n\n3. Create a new R Markdown document and give it a sensible title describing the chapter, such as `Equivalence Testing`. Delete everything below line 10 so you have a blank file to work with and save the file in your `Equivalence_testing` folder. \n\n4. The @dawtry_why_2015 data wrangling steps were quite long, so please save this clean version of the data to focus on screening data in this chapter: [Dawtry_2015_clean.csv](data/Dawtry_2015_clean.csv). You will also need to save the data from @lopez_visual_2023 if you have not downloaded it yet: [Lopez_2023.csv](data/Lopez_2023.csv). Right click the link and select \"save link as\", or clicking the link will save the files to your Downloads. Make sure that you save the files as \".csv\". Save or copy the files to your `data/` folder within `Equivalence_testing`.\n\nTo prepare for the activities, read and process the two key data files. You will also need to install the <pkg>TOSTER</pkg> package before you can load it as that is a new package we have not used before. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(correlation)\nlibrary(effectsize)\nlibrary(TOSTER)\n\n# Read the Dawtry_2015_clean.csv file \ndawtry_clean <- read_csv(\"data/Dawtry_2015_clean.csv\")\n\n# Read the Lopez_2023.csv file \nlopez_data <- read_csv(\"data/Lopez_2023.csv\")\n\n# recode condition\nlopez_clean <- lopez_data %>% \n  mutate(Condition_label = case_match(Condition,\n                                      0 ~ \"Control\",\n                                      1 ~ \"Experimental\"))\n```\n:::\n\n\n\n\n\n\nYou are now ready to start working on the chapter! \n\n## The logic behind equivalence testing\n\nThe standard approach to inferential statistics using frequentist probability is trying to reject a point-null value of zero, applied to whatever parameter you are interested in. In a t-test, this is a mean difference of zero as your test statistic/value. In a correlation, it is a correlation coefficient of zero as your test statistic/value. The *p*-value in the test represents the probability of observing the data, assuming that the null (that point-null value of zero) is true. You are always trying to reject the null hypothesis and indirectly accept the alternative hypothesis, but importantly you can never accept the null. Visually, it looks something like this: \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\nIn a two-tailed test, the null is precisely zero and you are trying to reject it in favour of the alternative hypothesis which can be any positive or negative value. In a one-tailed test, it follows the same logic, but instead of precisely zero, the null is the entire positive or negative region, meaning you want to reject values above or below zero depending which direction you predict. For many research questions, this logic holds to test for the presence of an effect by rejecting the null hypothesis. However, what about if your research question / prediction is interested in testing the null *itself* or a lack of effect? Unfortunately, you cannot test for the effect being precisely zero but you can use the procedure to test for effects too small to be practically or theoretically meaningful.  \n\nEquivalence testing [@harms_making_2018; @lakens_improving_2020; @lakens_equivalence_2018] flips the null hypothesis significance testing logic. In this setup, you set two boundaries representing your smallest effect size of interest (SESOI) and conduct two one-sided tests: one comparing your test statistic/value to the upper bound and one comparing your test statistic/value to the lower bound. If both tests are statistically significant, you can conclude the mean was within your bounds and it is practically equivalent to zero. \n\nThis procedure is usually referred to by the single name of equivalence testing, but you can apply it in two ways depending on your research question. In an equivalence test, you want to test whether your test statistic/value is smaller than your boundaries, i.e., you want to test for the absence of an effect. Conversely, in a minimal effects test you want to test whether your statistic/value is larger than your boundaries, i.e., you want to test for an effect exceeding your SESOI. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\nIn an equivalence test, the null hypothesis is split into two regions representing your SESOI. The two one-sided tests compare your test statistic/value to calculate whether it is significantly lower than the upper bound **and** significantly higher than the upper bound. If both tests are significant, you conclude it is statistically equivalent, given the boundaries you set. Conversely, a minimal effects test flips this procedure. Instead of a point-null in NHST, the null hypothesis is a region of effects representing your SESOI. The two one-sided tests calculate whether your test statistic/value is significantly lower than the lower bound and significantly higher than the higher bound. You are looking for the tests to be statistically significant to test the null region.\n\nJustifying your equivalence/minimal effects bounds is probably the most difficult decision you will make as it requires subject knowledge for what you would consider the smallest effect size of interest. For a non-exhaustive list, there are different strategies like: \n\n1. Your understanding of the applications / mechanisms (e.g., a clinically meaningful decrease in pain). \n\n2. Smallest effects from previous research (e.g., lower bound of individual study effect sizes or lower bound of a meta-analysis).\n\n3. Small telescopes (the effect size the original study had 33% power to detect).\n\n## Correlations \n\nTo apply the procedure to correlations, we will use the @dawtry_why_2015 data and the relationship between support for wealth redistribution and perceived fairness and satisfaction in the current system. For a starting point, we need to calculate the correlation coefficient as standard. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncorrelation(data = dawtry_clean, \n            select = \"fairness_satisfaction\", \n            select2 = \"redistribution\",  \n            method = \"pearson\", \n            alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1            |     Parameter2 |     r |         95% CI | t(303) |         p\n------------------------------------------------------------------------------------\nfairness_satisfaction | redistribution | -0.70 | [-0.75, -0.64] | -17.08 | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 305\n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Equivalence testing\n\nFor the first demonstration, we will conduct an equivalence test using the correlation coefficient we observed. The idea behind this function is that you can apply the procedure when you only have summary statistics and you do not need the raw data. In the `corsum_test()` function, we need to define: \n\n- `r` - The observed correlation coefficient. \n\n- `n` - The number of observation pairs, i.e., the sample size. \n\n- `alternative` - The hypothesis to test, including options like \"equivalence\" and \"minimal.effect\".\n\n- `method` - The type of correlation to calculate, including options like \"pearson\" and \"spearman\". \n\n- `null` - The null hypothesis or region to test against. If you provide a single value, it will test against symmetrical values, i.e., 0.2 will test against -0.2 and 0.2. If you want to specify asymmetrical values, you must enter a vector of numbers like `c(0, 0.2)`. \n\nTo apply this procedure to the correlation example, we can enter -0.70 for the Pearson correlation coefficient and 305 participants. The equivalence bounds is the hardest argument to set here, so we will use 0.2 as there is an idea called the \"crud factor\" where correlations smaller than 0.2 are likely noise (although @orben_crud_2020 critique this somewhat). \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncorsum_test(r = -0.70, \n            n = 305, \n            alternative = \"equivalence\", \n            method = \"pearson\", \n            null = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  x and y\nz = -11.549, N = 305, p-value = 1\nalternative hypothesis: equivalence\nnull values:\ncorrelation correlation \n        0.2        -0.2 \n90 percent confidence interval:\n -0.7451459 -0.6484676\nsample estimates:\n cor \n-0.7 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nIn this example, the *p*-value of the equivalence test is 1 which might sound strange, but we need to think of the procedure here. Remember in an equivalence test we want to test whether the test statistic is *smaller* than the boundaries. In this scenario, the observed test statistic is *r* = -0.70 (90% CI = [-0.75, -0.65]). The correlation is pretty large and beyond the lower bound of -0.2, so it is entirely within that null region.\n\n::: {.callout-note}\n#### Why is it a 90% CI? \n\nOne detail you might have noticed is that we use a 90% confidence interval instead of the standard 95%. If we want to maintain the standard alpha rate at 5%, a 90% confidence interval over two tests maintains the alpha rate at 5%. \n:::\n\n### Minimal effects testing\n\nFor this scenario, it would be more aligned with a minimal effects test as we want to calculate whether our effect exceeds our SESOI. This time, we will set the alternative argument as `\"minimal.effect\"`.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncorsum_test(r = -0.70, \n            n = 305, \n            alternative = \"minimal.effect\", \n            method = \"pearson\", \n            null = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  x and y\nz = -11.549, N = 305, p-value < 2.2e-16\nalternative hypothesis: minimal.effect\nnull values:\ncorrelation correlation \n        0.2        -0.2 \n90 percent confidence interval:\n -0.7451459 -0.6484676\nsample estimates:\n cor \n-0.7 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThis time, it is statistically significant as our observed correlation coefficient is significantly lower than our lower bound of -0.2. This means we can conclude the effect size exceeds our minimal effects test. \n\n### Plotting the tests\n\nTo help communicate your findings, or just help contextualise things for you, we can plot the results of these tests using one of two methods. First, the <pkg>TOSTER</pkg> package comes with a function to plot different tests that we can edit using <pkg>ggplot2</pkg> layers. \n\nThe first step is saving the plot object using the same values as we used for the equivalence test.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- plot_cor(r = -0.70, \n         n = 305, \n         method = \"pearson\", \n         type = \"cd\")\n\n# print the object\np\n```\n\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n\n\n\nThe default arguments here visualise the observed correlation coefficient with a range of confidence intervals. We can then add <pkg>ggplot2</pkg> layers to visualise the equivalence test or minimal effects test results, depending which way around you want to interpret the results.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np + scale_x_continuous(limits = c(-0.8, 0.2), \n                       breaks = seq(-0.8, 0.2, 0.2)) + \n  annotate(geom = \"rect\", \n           xmin = -0.2, xmax = 0.2, \n           ymin = I(0), ymax = I(100), # I() specifies values as percent of plot\n           alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n\n\n\nAlternatively, if you wanted a more minimalist look or you wanted to plot the results of multiple correlations, we can create our own version. The first step is saving the results of a `correlation()` object, specifying we want the 90% confidence interval. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsave_correlation <- correlation(data = dawtry_clean, \n            select = \"fairness_satisfaction\", \n            select2 = \"redistribution\",  \n            method = \"pearson\", \n            alternative = \"two.sided\",\n            ci = 0.9)\n```\n:::\n\n\n\n\n\n\nThis provides us with a data frame containing one row. This means we can take the results and feed it into <pkg>ggplot2</pkg>. We can use similar layers to customise our own version of the plot to help visualise the equivalence or minimal effects test. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsave_correlation %>% \n  ggplot(aes(y = r, x = \"\")) + # leave x blank\n  geom_point() + # correlation estimate\n  geom_errorbar(aes(ymin = CI_low, # 90% CI around r\n                    ymax = CI_high), \n                width = 0.2) + \n  labs(x = \"\",\n       y = \"Pearson's Correlation\") + \n  coord_flip() + # flip x and y axes\n  scale_y_continuous(limits = c(-0.8, 0.2), \n                       breaks = seq(-0.8, 0.2, 0.2)) + \n  annotate(geom = \"rect\", # add the box for the SESOI\n           ymin = -0.2, ymax = 0.2, \n           xmin = I(0), xmax = I(100),\n           alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n\n\n\n## t-tests\n\nTo apply the procedure to t-tests, we will use the @lopez_visual_2023 data and the difference in calories consumed between accurate and inaccurate visual cues.\n\n### Equivalence testing\n\nThere are two ways you can apply the equivalence testing procedure for t-tests. We are focusing on two groups here, but the function also works for paired samples and one-sample t-tests. We will start with the `t_TOST()` function which starts with similar arguments to the standard `t.test()` function: \n\n- `formula` - For two groups, we can use the standard `outcome ~ predictor` format. If you have paired samples or one-sample, you can use the `x` and `y` arguments. \n\n- `data` - The data frame you are using.  \n\n- `eqb` - The equivalence bounds you want to set. If you enter one number, it will create symmetrical bounds, such as -20 to 20. If you want asymmetrical bound, you would need to enter a vector of numbers.  \n- `eqbound_type` - The default option is to enter \"raw\" units, so whatever scale your outcome is on. For our example, this will be in calories. Your other option is \"smd\" for standardised mean difference, or Cohen's d. You can enter the equivalence bounds as standardised units but it comes with a little warning that there is potential bias.  \n- `hypothesis` - This is where you can create an equivalence test using \"EQU\" or a minimal effects test using \"MET\". We will come back to minimal effects in the next section. \n\nThe main argument to explain here is using 57 calories for the equivalence bounds. Remember this is a t-test, so we want to see whether one group is larger (or smaller) than the other. Setting the equivalence bounds is the single most difficult part here but @lopez_visual_2023 explain that they were interested in detecting an effect at least half as large as the original Wansink et al. study. Therefore, in an equivalence test, we would ask the question whether the observed effect size is smaller than 57 calories difference. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_TOST(formula = F_CaloriesConsumed ~ Condition_label, \n       data = lopez_clean, \n       eqb = 57, \n       eqbound_type = \"raw\",\n       hypothesis = \"EQU\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWelch Two Sample t-test\n\nThe equivalence test was non-significant, t(453.45) = -0.47, p = 0.68\nThe null hypothesis test was significant, t(453.45) = -4.86, p < 0.01\nNHST: reject null significance hypothesis that the effect is equal to zero \nTOST: don't reject null equivalence hypothesis\n\nTOST Results \n                 t    df p.value\nt-test     -4.8578 453.4 < 0.001\nTOST Lower -0.4661 453.4   0.679\nTOST Upper -9.2495 453.4 < 0.001\n\nEffect Sizes \n               Estimate       SE                 C.I. Conf. Level\nRaw            -63.0495 12.97908 [-84.4419, -41.6571]         0.9\nHedges's g(av)  -0.4513  0.09445   [-0.6059, -0.2963]         0.9\nNote: SMD confidence intervals are an approximation. See vignette(\"SMD_calcs\").\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe output is busier than correlations, so we will walk through the three sections. The first explains the summary of the equivalence tests. You get both the equivalence test and a traditional t-test. Here, the traditional t-test is significant (we can reject 0) but the equivalence test is non-significant, meaning we cannot conclude the effect was statistically equivalent, given our bounds. \n\nThe second section adds context to this as you see the output for all three tests. The t-test is significant to reject zero. We then have the two one-sided tests where one is significant (we can reject the upper bound), but the other is non-significant. Both need to be significant to conclude equivalence. \n\nFinally, we have a summary of the effect sizes. You get the raw / unstandardised effect size and it's 90% CI. For our equivalence bounds of -57 to 57, the upper bound of the 90% CI (-41.66) extends into the equivalence bounds, so that's why the test is non-significant. You also get Hedge's g as a standardised effect size. \n\nBriefly, there is a second, more minimalist function to calculate the equivalence test called `simple_htest()`. This is supposed to look closer to the output from a traditional t-test but the conclusion is the same. You just get one test (the smaller of the two one-sided tests) and a summary of the boundaries. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimple_htest(formula = F_CaloriesConsumed ~ Condition_label, \n       data = lopez_clean, \n       mu = 57, \n       alternative = \"e\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  F_CaloriesConsumed by Condition_label\nt = -0.4661, df = 453.45, p-value = 0.6793\nalternative hypothesis: equivalence\nnull values:\ndifference in means difference in means \n                -57                  57 \n90 percent confidence interval:\n -84.44188 -41.65710\nsample estimates:\nmean of x mean of y \n 196.6818  259.7313 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Minimal effects testing\n\nFor the framing of @lopez_visual_2023, it potentially makes more sense to calculate a minimal effects test if we are interested in the effect being at least as large as half the original effect size. In other words, we want to see whether the effect is 57 calories or greater, rather than smaller than 57 calories. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_TOST(formula = F_CaloriesConsumed ~ Condition_label, \n       data = lopez_clean, \n       eqb = 57, \n       eqbound_type = \"raw\",\n       hypothesis = \"MET\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWelch Two Sample t-test\n\nThe minimal effect test was non-significant, t(453.45) = -9.2, p = 0.32\nThe null hypothesis test was significant, t(453.45) = -4.86, p < 0.01\nNHST: reject null significance hypothesis that the effect is equal to zero \nTOST: don't reject null MET hypothesis\n\nTOST Results \n                 t    df p.value\nt-test     -4.8578 453.4 < 0.001\nTOST Lower -0.4661 453.4   0.321\nTOST Upper -9.2495 453.4       1\n\nEffect Sizes \n               Estimate       SE                 C.I. Conf. Level\nRaw            -63.0495 12.97908 [-84.4419, -41.6571]         0.9\nHedges's g(av)  -0.4513  0.09445   [-0.6059, -0.2963]         0.9\nNote: SMD confidence intervals are an approximation. See vignette(\"SMD_calcs\").\n```\n\n\n:::\n:::\n\n\n\n\n\n\nIn changing the `hypothesis` argument to \"MET\", we still get all the same output but the framing changes. Instead of testing whether the observed effect is *within* the equivalence bounds, we test whether the effect is *outwith* the equivalence bounds. We get a similar conclusion here where the traditional t-test is significant and we can reject the point null of zero. However, the minimal effects test is non-significant and our effect does not exceed the bounds. \n\n### Plotting the tests\n\nThe plotting options are also a little nicer here as there are built-in visualisations for equivalence tests. First, we need to save the initial test object. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlopez_EQU <- t_TOST(formula = F_CaloriesConsumed ~ Condition_label, \n                    data = lopez_clean, \n                    eqb = 57, \n                    eqbound_type = \"raw\",\n                    hypothesis = \"EQU\")\n```\n:::\n\n\n\n\n\n\nWe can then pass the object to `plot()` to create different types of visualisation. The first is a simple dot-and-whisker plot we created ourselves for the correlation. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(lopez_EQU, \n     type = \"simple\", \n     layout = \"combined\")\n```\n\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n\n\n\nThe second is a density plot like we saw for correlations, but this time the equivalence bounds are added automatically. \n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(lopez_EQU, \n     type = \"cd\")\n```\n\n::: {.cell-output-display}\n![](appendix-c-equivalence_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n\n\n\n\n\nBoth visualisations reinforce the conclusion that we have a traditionally significant result where we can reject a point-null, but the effect estimate and it's precision through the 90% CI does not exceed the equivalence bounds we set. \n",
    "supporting": [
      "appendix-c-equivalence_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}